### ISSUE TITLE
Model Json parsing issue

### ISSUE THREAD

**Issue by Xefyr0** [OE100/ReHooked#2]
When booting up Monifactory, it seems that ReHooked has an issue with one of its asset jsons.
The following error appears in the console every time on startup:
```
[Worker-ResourceReload-1/ERROR] [minecraft/ModelManager]: Failed to load model rehooked:models/item/hook.json
com.google.gson.JsonSyntaxException: Missing model, expected to find a string
```

**Comment by ghost** [comment]
I want to say that this is fine, it's just the file I use to generate all the hook item texture variations as I was too lazy to create a file for every hook type, the problem is maybe that the "original" missing texture base hook doesn't have an associated item that actually uses it or something, so it throws this error message.

Honestly as long as the actual textures on my items work this file has served it's purpose 🤷‍♂️
